import React from 'react';
import styled from 'styled-components';
import { Button, Card, Container } from './components/SharedComponents';

const PageContainer = styled.div`
  min-height: 100vh;
  padding: 2rem 0 4rem 0;
`;

const Title = styled.h1`
  font-size: 2.5rem;
  font-weight: 800;
  color: #2c3e50;
  margin-bottom: 1rem;
  text-align: center;

  @media (max-width: 768px) {
    font-size: 2rem;
  }
`;

const LastUpdated = styled.p`
  text-align: center;
  color: #7f8c8d;
  font-size: 0.875rem;
  margin-bottom: 3rem;
  font-style: italic;
`;

const ContentCard = styled(Card)`
  padding: 3rem;
  max-width: 900px;
  margin: 0 auto 2rem;

  @media (max-width: 768px) {
    padding: 2rem 1.5rem;
  }
`;

const Section = styled.section`
  margin-bottom: 2.5rem;
`;

const SectionTitle = styled.h2`
  font-size: 1.5rem;
  font-weight: 700;
  color: #2c3e50;
  margin-bottom: 1rem;
`;

const Paragraph = styled.p`
  font-size: 1rem;
  color: #5a6c7d;
  line-height: 1.8;
  margin-bottom: 1rem;
`;

const List = styled.ul`
  list-style: disc;
  padding-left: 2rem;
  margin-bottom: 1rem;
`;

const ListItem = styled.li`
  font-size: 1rem;
  color: #5a6c7d;
  line-height: 1.8;
  margin-bottom: 0.5rem;
`;

const BackButton = styled.div`
  text-align: center;
  margin-top: 3rem;
`;

const WarningBox = styled.div`
  background: rgba(231, 76, 60, 0.1);
  border: 2px solid rgba(231, 76, 60, 0.3);
  border-radius: 8px;
  padding: 1.5rem;
  margin: 2rem 0;
`;

const WarningTitle = styled.h3`
  font-size: 1.125rem;
  font-weight: 700;
  color: #c0392b;
  margin-bottom: 0.75rem;
`;

const WarningText = styled.p`
  font-size: 0.9375rem;
  color: #5a6c7d;
  line-height: 1.7;
  margin: 0.5rem 0;
`;

const TermsOfService = ({ onBack }) => {
  return (
    <PageContainer>
      <Container maxWidth="1200px">
        <Title>Terms of Service</Title>
        <LastUpdated>Last Updated: February 12, 2026</LastUpdated>

        <ContentCard>
          <WarningBox>
            <WarningTitle>[exclamationmark.triangle] Critical Disclaimer</WarningTitle>
            <WarningText>
              <strong>This is a student portfolio project for entertainment and educational purposes only.</strong>
            </WarningText>
            <WarningText>
              This tool is NOT a scientifically validated psychometric instrument. It should NOT be used for professional
              career counseling, employment screening, hiring decisions, or any high-stakes purposes.
            </WarningText>
          </WarningBox>

          <Section>
            <SectionTitle>1. Acceptance of Terms</SectionTitle>
            <Paragraph>
              By accessing and using Tech 16 Personalities ("the Service"), you accept and agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not use the Service.
            </Paragraph>
          </Section>

          <Section>
            <SectionTitle>2. Description of Service</SectionTitle>
            <Paragraph>
              Tech 16 Personalities is a rule-based personality assessment tool designed as a student portfolio project.
              The Service provides:
            </Paragraph>
            <List>
              <ListItem>A 40-question quiz to assess personality preferences</ListItem>
              <ListItem>Personality type results based on predefined algorithms</ListItem>
              <ListItem>Career recommendations for technical roles</ListItem>
              <ListItem>Educational information about personality frameworks</ListItem>
            </List>
          </Section>

          <Section>
            <SectionTitle>3. Limitations and Disclaimers</SectionTitle>

            <SectionTitle style={{ fontSize: '1.125rem', marginTop: '1.5rem' }}>
              3.1 Not Scientifically Validated
            </SectionTitle>
            <Paragraph>
              This tool has NOT undergone peer review, empirical validation studies, or professional psychometric testing.
              Results are generated by rule-based algorithms created by a student developer.
            </Paragraph>

            <SectionTitle style={{ fontSize: '1.125rem', marginTop: '1.5rem' }}>
              3.2 Not Professional Career Counseling
            </SectionTitle>
            <Paragraph>
              This Service is NOT a substitute for professional career counseling, vocational assessment, or licensed
              psychological services. For professional career guidance, consult with:
            </Paragraph>
            <List>
              <ListItem>Licensed career counselors</ListItem>
              <ListItem>Certified professionals administering validated assessments (e.g., Strong Interest Inventory, MBTI)</ListItem>
              <ListItem>University career services</ListItem>
              <ListItem>Professional vocational psychologists</ListItem>
            </List>

            <SectionTitle style={{ fontSize: '1.125rem', marginTop: '1.5rem' }}>
              3.3 No Hiring or Employment Use
            </SectionTitle>
            <Paragraph>
              <strong>PROHIBITED USE:</strong> This tool must NOT be used for employment screening, hiring decisions,
              personnel selection, or any workplace assessment purposes. Such use may violate employment laws and
              professional testing standards.
            </Paragraph>

            <SectionTitle style={{ fontSize: '1.125rem', marginTop: '1.5rem' }}>
              3.4 Entertainment and Educational Purpose Only
            </SectionTitle>
            <Paragraph>
              This Service is designed for personal exploration, self-reflection, and learning about personality
              frameworks. Results should be interpreted as suggestions for self-discovery, not as definitive assessments.
            </Paragraph>
          </Section>

          <Section>
            <SectionTitle>4. No Warranties</SectionTitle>
            <Paragraph>
              The Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind, either express or implied,
              including but not limited to:
            </Paragraph>
            <List>
              <ListItem>Accuracy, reliability, or validity of results</ListItem>
              <ListItem>Fitness for any particular purpose</ListItem>
              <ListItem>Career success or satisfaction</ListItem>
              <ListItem>Continuous availability or error-free operation</ListItem>
            </List>
          </Section>

          <Section>
            <SectionTitle>5. Limitation of Liability</SectionTitle>
            <Paragraph>
              To the fullest extent permitted by law, the creators of Tech 16 Personalities shall not be liable for:
            </Paragraph>
            <List>
              <ListItem>Career decisions made based on quiz results</ListItem>
              <ListItem>Educational or professional choices influenced by recommendations</ListItem>
              <ListItem>Any direct, indirect, incidental, or consequential damages arising from use of the Service</ListItem>
              <ListItem>Loss of data, time, or opportunities</ListItem>
            </List>
          </Section>

          <Section>
            <SectionTitle>6. User Responsibilities</SectionTitle>
            <Paragraph>
              By using this Service, you agree to:
            </Paragraph>
            <List>
              <ListItem>Use the Service for entertainment and educational purposes only</ListItem>
              <ListItem>Not rely on results for major life or career decisions without consulting professionals</ListItem>
              <ListItem>Not use the Service for hiring, employment screening, or professional assessment</ListItem>
              <ListItem>Understand that results are generated by algorithms, not human experts</ListItem>
              <ListItem>Take full responsibility for any actions taken based on quiz results</ListItem>
            </List>
          </Section>

          <Section>
            <SectionTitle>7. Intellectual Property</SectionTitle>
            <Paragraph>
              All content, algorithms, design, and materials on this Service are the intellectual property of the
              creator and are protected by copyright laws. This is a student portfolio project intended for
              demonstration purposes.
            </Paragraph>
          </Section>

          <Section>
            <SectionTitle>8. Data Collection and Privacy</SectionTitle>
            <Paragraph>
              Your quiz responses are stored locally in your browser and are not transmitted to our servers.
              For more information, please read our Privacy Policy.
            </Paragraph>
          </Section>

          <Section>
            <SectionTitle>9. No Professional Relationship</SectionTitle>
            <Paragraph>
              Use of this Service does not create any professional relationship (counselor-client, psychologist-patient,
              advisor-advisee) between you and the Service creators.
            </Paragraph>
          </Section>

          <Section>
            <SectionTitle>10. Modifications to Terms</SectionTitle>
            <Paragraph>
              We reserve the right to modify these Terms of Service at any time. The "Last Updated" date will reflect
              the most recent changes. Continued use of the Service after changes constitutes acceptance of the modified terms.
            </Paragraph>
          </Section>

          <Section>
            <SectionTitle>11. Modifications to Service</SectionTitle>
            <Paragraph>
              As a student project, this Service may be modified, updated, or discontinued at any time without notice.
              We make no guarantees about the ongoing availability of the Service.
            </Paragraph>
          </Section>

          <Section>
            <SectionTitle>12. Governing Law</SectionTitle>
            <Paragraph>
              These Terms of Service shall be governed by and construed in accordance with applicable laws.
              This is a non-commercial student project.
            </Paragraph>
          </Section>

          <Section>
            <SectionTitle>13. Contact Information</SectionTitle>
            <Paragraph>
              This is a student portfolio project. For questions about these Terms of Service, please visit the
              project's GitHub repository or contact the creator through their portfolio website.
            </Paragraph>
          </Section>

          <WarningBox style={{ marginTop: '3rem' }}>
            <WarningTitle>Final Reminder</WarningTitle>
            <WarningText>
              By using this Service, you acknowledge that you have read, understood, and agree to these Terms of Service,
              including all disclaimers and limitations. You understand that this is a student project for entertainment
              and educational purposes only, and you will not use it for professional, employment, or high-stakes decisions.
            </WarningText>
          </WarningBox>
        </ContentCard>

        <BackButton>
          <Button onClick={onBack} variant="outline" size="large">
            Back to Home
          </Button>
        </BackButton>
      </Container>
    </PageContainer>
  );
};

export default TermsOfService;
